### PR TITLE
Inserting exact attribute in route

### PR DESCRIPTION
**Pull request by andrelmlins**
This will be very useful for forcing an exact pathname in the string

### CODE REVIEW

**Comment by iminside** [comment]
Hi André,
thanks for your PR, I also thought about this functionality and came to the following conclusions:

- when we create a route based on a regular expression, this parameter becomes useless
```ts
const pageRoute = route(/\/page/, pageFractal, true)
//                                             ^^^^ or false
//                                             irrelevant
```
- when we create a route based on a generator and we need to specify a `this`, we are forced to define an `exact`, because `thisArg` is the third parameter (after `exact`). If we swap these parameters, then a similar situation will arise - when we need to define an `exact`, we will have to specify `thisArg`.
```ts
const pageRoute = route('/page', function*(){
    while(true){
        yield 'page content'
    }
}, true /*or false*/, this)
// ^^^^ we must definitely define the parameter
```
- since the string route is still converted to a regular expression, the `$` character will work as an `exact = true`. At first glance, this is not obvious, so I think it is worth mentioning this in the readme.
```ts
const pageRoute = route('/page$', pageFractal)
//                            ^ it work as exact = true
```

In the future, I think it is worth adding a simple string route parser, which, according to certain rules, will parse the string into a regular expression, e.g.
```ts
'/user/:id$' /* -- parse to --> */ /^user\/(.+?)$/
```

**Comment by andrelmlins** [comment]
Hi Denis, great observations.

I believe that for string the exact is very important, so let's try to come up with a possible one that is more pleasant.

What do you think of this solution? Being one more option for the first parameter.

```ts
const pageRoute = route({
  path: '/path',
  exact: false
}, pageFractal)
```

The exact default would be true when it is a simple string. If you find it interesting I modify it and insert it in the README.

**Comment by iminside** [comment]
Andrey, why don't you like this solution? 
```ts
const pageRoute = route('/page$', pageFractal)
```
I think this is a concise and pleasant way to indicate the end of a path, especially when the developer knows it will be converted to a regex under the hood.

I believe that by default this parameter should be false, because very often routes are nested and only occasionally we need to specify precisely that "the path must end here".

```ts
const appRoute = route('/app', function* () {
    while (true) {
        yield <div>{yield* usersRoute}</div>
    }
})

const usersRoute = route('/users', function* () {
    while (true) {
        yield <div>{yield* usersCreateRoute}</div>
    }
})

const usersCreateRoute = route('/create$', function* () {
    while (true) {
        yield <div>Content</div>
    }
})
```
In your version
```ts
const appRoute = route({path: '/app', exact: false}, function* () {
    while (true) {
        yield <div>{yield* usersRoute}</div>
    }
})

const usersRoute = route({path: '/users', exact: false}, function* () {
    while (true) {
        yield <div>{yield* usersCreateRoute}</div>
    }
})

const usersCreateRoute = route('/create', function* () {
    while (true) {
        yield <div>Content</div>
    }
})
```
I suggest we leave this request open for discussion, pause and think about it a bit. 
How do you think?

**Comment by andrelmlins** [comment]
great, I understand your solution. I will close this pull request and create another one

**Pull request closed without merging**
